/**
 * Share cards — the og:image half of the Open Graph tags in Base.astro.
 *
 * Every hero on this site is WebP, and LinkedIn's crawler does not read WebP:
 * it drops the image and posts a bare text card. Facebook and X cope with it,
 * LinkedIn does not, and LinkedIn is where these articles actually get shared.
 * So og:image points at a JPEG derivative rather than at the WebP the page
 * itself displays — the page keeps the small file, the crawler gets one it can
 * open.
 *
 * Derivatives live in public/og/ and mirror the path under public/assets/, so
 * two images with the same name in different folders cannot collide. They are
 * generated by `npm run og:images` and committed; `npm run check:og` fails the
 * build if a page points at one that was never generated.
 */

/** The 1.91:1 box Facebook, LinkedIn and X all render a large card into. */
export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;

/** Root-relative path of the share card for a root-relative /assets/ image. */
export function shareCardPath(src) {
  const asset = src.replace(/^\//, "").replace(/^assets\//, "");
  return `/og/${asset.replace(/\.[^.]+$/, "")}.jpg`;
}

/**
 * Resolve an og:image to the card a crawler should fetch.
 *
 * An absolute URL passes through untouched — that is somebody else's file and
 * there is nothing to derive from it, so it also gets no dimensions.
 *
 * @param {string} src Root-relative /assets/ path, or an absolute URL.
 * @returns {{ url: string, width?: number, height?: number, type?: string }}
 */
export function shareCard(src) {
  if (/^https?:\/\//.test(src)) return { url: src };

  return {
    url: shareCardPath(src),
    width: OG_WIDTH,
    height: OG_HEIGHT,
    type: "image/jpeg",
  };
}
